version: '3.8'

services:
  portainer:
        image: portainer/portainer-ce:latest
        container_name: portainer
        restart: unless-stopped
        networks:
          - default
        # ports:
        #    - "9000:9000"  # Uncomment this to enable HTTP on port 9000
        #     - "9443:9443"  # Uncomment this to enable HTTPS on port 9443
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - ./data:/data

  portainer_tunnel:
    build:
      context: .
      dockerfile: DockerfileTunnel
    container_name: portainer_tunnel
    restart: unless-stopped
    volumes:
      - ~/.cloudflared:/root/.cloudflared
    networks:
      - default

networks:
  default: